# version: '3.9'
# services:
#   app:
#     build: 
#       context: .
#       args: 
#         - DEV=true
#     ports:
#       - "8000:8000"   #maps port from local to container
#     volumes:
#       - ./app:/app  #map app directory from project to our container
#     command: >
#       sh -c "python manage.py runserver 0.0.0.0:8000"

version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"